name: Build site
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache output
      path: schauinsland2022
    - run: pip install -r requirements.txt
    - run: ./makeall.sh
      env:
        DHV_USERNAME: ${{ secrets.DHV_USERNAME }}
        DHV_PASSWORD: ${{ secrets.DHV_PASSWORD }}
